version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "04:00"
      timezone: Europe/Berlin
    open-pull-requests-limit: 5
    groups:
      python-routine:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
      python-major:
        patterns:
          - "*"
        update-types:
          - major
    commit-message:
      prefix: chore
      include: scope

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "04:20"
      timezone: Europe/Berlin
    open-pull-requests-limit: 5
    groups:
      actions-routine:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
      actions-major:
        patterns:
          - "*"
        update-types:
          - major
    commit-message:
      prefix: chore
      include: scope
